In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df =pd.read_csv("homeprices.csv")

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms.median()

4.0

In [5]:
import math 
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [6]:
df.bedrooms=df.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600    2600.0   20  550000
1  3000    3000.0   15  565000
2  3200    3200.0   18  610000
3  3600    3600.0   30  595000
4  4000    4000.0    8  760000
5  4100    4100.0    8  810000

In [7]:
reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [8]:
reg.coef_

array([   66.50427557,    66.50427557, -5463.92203827])

In [9]:
reg.intercept_

284042.16390733153

In [10]:
reg.predict([[3000,3,40]])

array([265197.62191149])

In [11]:
66.50427557*3000+66.50427557*3-5463.92203827*40+284042.16390733153

265197.6219132416

In [12]:
reg.predict([[2500,4,5]])

array([423249.2597417])