In [22]:
import pandas as pd
import  numpy as np

In [23]:
df =pd.read_excel("homeprice.xlsx")
df

Area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [24]:
from sklearn import linear_model
model =linear_model.LinearRegression()
model.fit(df[['Area']],df.Price)

LinearRegression()

In [25]:
model.coef_

array([135.78767123])

In [26]:
model.intercept_

180616.43835616432

In [27]:
model.predict([[5000]])

array([859554.79452055])

In [28]:
import pickle

In [29]:
with open("model_pickle","wb") as f:
    pickle.dump(model,f)

In [30]:
with open("model_pickle","rb") as f:
    mp=pickle.load(f)

In [31]:
mp.predict([[5000]])

array([859554.79452055])

In [32]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)

In [33]:
import joblib

In [34]:
mj=joblib.dump(model,"model_joblib")

In [35]:
mj.predict([[5000]])

AttributeError: 'list' object has no attribute 'predict'